name: Feature Request
description: Suggest an idea or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Is your feature request related to a problem? Please describe.

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you’d like.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you’ve considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots.
